twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        picture_path: "build/images/images/"
        icons_path: "build/images/icons/"
        upload_path: "build/images/uploads/"

when@test:
    twig:
        strict_variables: true
